# Generated by Django 5.2.5 on 2025-09-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionOrdenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=50)),
                ('orden_por_defecto', models.CharField(choices=[('fecha', 'Por fecha de creación'), ('dificultad', 'Por dificultad'), ('puntos', 'Por puntos'), ('aleatorio', 'Aleatorio'), ('prioridad', 'Por prioridad'), ('popularidad', 'Por popularidad')], default='fecha', help_text='Orden por defecto para mostrar retos', max_length=20)),
                ('incluir_aleatorios', models.BooleanField(default=True, help_text='¿Incluir retos marcados como aleatorios?')),
                ('max_retos_por_pagina', models.IntegerField(default=10, help_text='Número máximo de retos por página')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Ordenamiento',
                'verbose_name_plural': 'Configuraciones de Ordenamiento',
            },
        ),
        migrations.AddField(
            model_name='reto',
            name='mostrar_aleatorio',
            field=models.BooleanField(default=False, help_text='¿Mostrar este reto en orden aleatorio?'),
        ),
        migrations.AddField(
            model_name='reto',
            name='orden_prioridad',
            field=models.IntegerField(default=0, help_text='Prioridad de ordenamiento (mayor número = más arriba)'),
        ),
    ]
