# Generated by Django 5.2.5 on 2025-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0002_configuracionordenamiento_reto_mostrar_aleatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='max_intentos',
            field=models.IntegerField(default=3, help_text='Número máximo de intentos permitidos por usuario'),
        ),
    ]
