# Generated by Django 5.2.5 on 2025-09-09 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0003_reto_max_intentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='max_intentos',
            field=models.IntegerField(default=3, help_text='Número máximo de intentos permitidos por usuario (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
