# Generated by Django 5.2.5 on 2025-09-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0004_alter_reto_max_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto de la respuesta alternativa')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de esta alternativa', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='¿Esta alternativa está activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_alternativas', to='retos.reto')),
            ],
            options={
                'verbose_name': 'Respuesta Alternativa',
                'verbose_name_plural': 'Respuestas Alternativas',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
