# Generated by Django 5.2.6 on 2025-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0005_respuestaalternativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='ejemplo_entrada',
            field=models.TextField(blank=True, help_text='Ejemplo de cómo escribir la respuesta (no revela la solución)'),
        ),
    ]
