# Generated by Django 5.2.5 on 2025-09-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0006_reto_ejemplo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='icono_por_defecto',
            field=models.CharField(blank=True, choices=[('🧩', '🧩 Puzzle'), ('🔢', '🔢 Números'), ('🧮', '🧮 Cálculo'), ('🎯', '🎯 Objetivo'), ('💡', '💡 Idea'), ('🎲', '🎲 Dados'), ('📊', '📊 Gráficos'), ('🔍', '🔍 Búsqueda'), ('⚡', '⚡ Rápido'), ('🏆', '🏆 Premio'), ('🎨', '🎨 Arte'), ('🌐', '🌐 Global')], help_text='Selecciona un icono por defecto si no tienes imagen personal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='imagen_reto',
            field=models.ImageField(blank=True, help_text='Sube una imagen relacionada con el reto (opcional)', null=True, upload_to='retos/'),
        ),
    ]
