# Generated by Django 5.2.5 on 2025-09-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar_por_defecto',
            field=models.CharField(blank=True, choices=[('👨', '👨 Hombre'), ('👩', '👩 Mujer'), ('👨\u200d💼', '👨\u200d💼 Profesional'), ('👩\u200d💼', '👩\u200d💼 Profesional'), ('👨\u200d🎓', '👨\u200d🎓 Estudiante'), ('👩\u200d🎓', '👩\u200d🎓 Estudiante'), ('👨\u200d💻', '👨\u200d💻 Desarrollador'), ('👩\u200d💻', '👩\u200d💻 Desarrolladora')], help_text='Selecciona un avatar por defecto si no tienes foto personal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Sube una foto personalizada o deja vacío para usar avatar por defecto', null=True, upload_to='perfiles/'),
        ),
    ]
