# Generated by Django 5.2.5 on 2025-09-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intento',
            unique_together=set(),
        ),
    ]
